/* Auto-generated by scripts/gen_arduboy_avr_roms.py. */
#ifndef APP_ARDUBOY_AVR_ROM_H
#define APP_ARDUBOY_AVR_ROM_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    const char *name;
    const char *hex;
} ArduboyAvrRom;

extern const ArduboyAvrRom gArduboyAvrRoms[];
extern const unsigned int gArduboyAvrRomCount;

#ifdef __cplusplus
}
#endif

#endif /* APP_ARDUBOY_AVR_ROM_H */
