#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import re
import sys


def _sanitize_symbol(name: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not safe:
        safe = "rom"
    if safe[0].isdigit():
        safe = f"rom_{safe}"
    return safe


def _c_escape(line: str) -> str:
    return line.replace("\\", "\\\\").replace("\"", "\\\"")


def _write_header(path: Path) -> None:
    header = """\
/* Auto-generated by scripts/gen_arduboy_avr_roms.py. */
#ifndef APP_ARDUBOY_AVR_ROM_H
#define APP_ARDUBOY_AVR_ROM_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    const char *name;
    const char *hex;
} ArduboyAvrRom;

extern const ArduboyAvrRom gArduboyAvrRoms[];
extern const unsigned int gArduboyAvrRomCount;

#ifdef __cplusplus
}
#endif

#endif /* APP_ARDUBOY_AVR_ROM_H */
"""
    path.write_text(header, encoding="ascii")


def _write_source(path: Path, roms: list[tuple[str, str]]) -> None:
    lines: list[str] = []
    lines.append("/* Auto-generated by scripts/gen_arduboy_avr_roms.py. */")
    lines.append('#include "arduboy_avr_rom.h"')
    lines.append("")

    for name, hex_text in roms:
        symbol = _sanitize_symbol(name)
        lines.append(f"static const char gArduboyAvrHex_{symbol}[] =")
        if hex_text:
            for line in hex_text.splitlines():
                lines.append(f"\"{_c_escape(line)}\\n\"")
        else:
            lines.append("\"\"")
        lines.append(";")
        lines.append("")

    if roms:
        lines.append("const ArduboyAvrRom gArduboyAvrRoms[] = {")
        for name, _ in roms:
            symbol = _sanitize_symbol(name)
            lines.append(f"    {{ \"{_c_escape(name)}\", gArduboyAvrHex_{symbol} }},")
        lines.append("};")
        lines.append("const unsigned int gArduboyAvrRomCount = "
                     "sizeof(gArduboyAvrRoms) / sizeof(gArduboyAvrRoms[0]);")
    else:
        lines.append("const ArduboyAvrRom gArduboyAvrRoms[] = {")
        lines.append("    { 0, 0 },")
        lines.append("};")
        lines.append("const unsigned int gArduboyAvrRomCount = 0;")

    lines.append("")
    path.write_text("\n".join(lines), encoding="ascii")


def main() -> int:
    root = Path(__file__).resolve().parents[3]
    games_dir = root / "src" / "app" / "opencv" / "game"
    out_c = root / "src" / "app" / "app" / "arduboy_avr_rom.c"
    out_h = root / "src" / "app" / "app" / "arduboy_avr_rom.h"

    if not games_dir.exists():
        print(f"Missing games directory: {games_dir}", file=sys.stderr)
        return 1

    roms: list[tuple[str, str]] = []
    for path in sorted(games_dir.glob("*.hex")):
        name = path.stem
        text = path.read_text(encoding="ascii", errors="ignore")
        roms.append((name, text))

    _write_header(out_h)
    _write_source(out_c, roms)
    print(f"Wrote {out_c} and {out_h} from {games_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
